apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-prometheus-db-prometheus-prometheus-1
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dev/shm/pv2"
